version: "2.1"
services:
  cms-db:
    image: "mysql:5.6"
    container_name: "on-demand-cms-db"
    # volumes:
    #   - "./xibo.sql:/docker-entrypoint-initdb.d/xibo.sql"
    environment:
      - "MYSQL_DATABASE=cms"
      - "MYSQL_USER=cms"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_PASSWORD=password"
  cms-xmr:
    image: "xibosignage/xibo-xmr:release-0.8"
    ports:
      - "9505:9505"
  cms-web:
    image: "xibosignage/xibo-cms:release-2.3.7"
    links:
      - "cms-db:mysql"
      - "cms-xmr:50001"
    environment:
      - "XMR_HOST=cms-xmr"
      - "MYSQL_PASSWORD=password"
    ports:
      - "80:80"
    volumes:
      - "./library:/var/www/cms/library:Z"
  cms-quickchart:
    image: "ianw/quickchart"
