package at.htl.ondemand.model.form;

import org.jboss.resteasy.annotations.providers.multipart.PartType;

import javax.ws.rs.FormParam;
import javax.ws.rs.core.MediaType;

public class LayoutForm {

    @FormParam("name")
    @PartType(MediaType.TEXT_PLAIN)
    public String name;

    @FormParam("description")
    @PartType(MediaType.TEXT_PLAIN)
    public String description;

    public LayoutForm(String name) {
        this.name = name;
        this.description = "This Layout is generated by on-demand";
    }
}
